kind: Service
apiVersion: v1
metadata:
  name: fineract-cn-identity
spec:
  selector:
    app: fineract-cn-identity
  ports:
    - name: http
      protocol: TCP
      port: 2021
      targetPort: httpport
    - name: httpdebug
      protocol: TCP
      port: 5005
      targetPort: debugport

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-cn-identity
  labels:
    app: fineract-cn-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fineract-cn-identity
  template:
    metadata:
      labels:
        app: fineract-cn-identity
    spec:
      containers:
        - name: fineract-cn-identity
          image: registry.dev.redbee.io/fineract-cn-identity:latest
          imagePullPolicy: Always
          env:
            - name: "server.port"
              value: "2021"
            - name: "server.max-http-header-size"
              value: "16384"
            - name: "spring.cloud.config.uri"
              value: "http://fineract-cn-cloud-config-server:8888"
            - name: "spring.cloud.config.profile"
              value: "default"
          ports:
            - name: httpport
              containerPort: 2021
            - name: debugport
              containerPort: 5005
          resources:
            requests:
              memory: 1Gi
              cpu: 0.1
            limits:
              memory: 2Gi
              cpu: 1
      imagePullSecrets:
        - name: docker.redbee

---
